#!name=常用脚本获取Cookie合集
#!desc=常用脚本获取cookies合集, 获取成功后关闭模块

[Script]
贴吧_获取cookie1 = type=http-request,pattern=^https?:\/\/(c\.tieba\.baidu\.com|180\.97\.\d+\.\d+)\/c\/s\/login,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/tieba/tieba_signin.js
贴吧_获取cookie2 = type=http-request,pattern=^https?:\/\/c\.tieba\.baidu\.com\/c\/s\/channelIconConfig,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/tieba/tieba_signin.js
贴吧_获取cookie3 = type=http-request,pattern=^https?:\/\/tiebac\.baidu\.com\/c\/u\/follow\/getFoldedMessageUserInfo,script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/tieba/tieba_signin.js

什么值得买_获取cookie = script-path=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/smzdm/smzdm_daily.js,type=http-request,requires-body=false,pattern=^https?:\/\/user-api\.smzdm\.com\/checkin$

QQ音乐_获取cookie1 = type=http-request,pattern=https://c6.y.qq.com/shop/fcgi-bin/fcg_get_order?,script-path=https://raw.githubusercontent.com/WowYiJiu/Personal/main/Script/qqMusic.js
QQ音乐_获取cookie2 = type=http-request,pattern=https://u6.y.qq.com/cgi-bin/musics.fcg?,script-path=https://raw.githubusercontent.com/WowYiJiu/Personal/main/Script/qqMusic.js

阿里云盘_获取cookie = type=http-request,requires-body=true,pattern=^https:\/\/(auth|aliyundrive)\.alipan\.com\/v2\/account\/token,script-path=https://gist.githubusercontent.com/Sliverkiss/33800a98dcd029ba09f8b6fc6f0f5162/raw/aliyun.js

[MITM]
hostname = %APPEND% c.tieba.baidu.com, tiebac.baidu.com, user-api.smzdm.com, *.y.qq.com, auth.alipan.com, auth.aliyundrive.com
